image:
  - Visual Studio 2017
  - Ubuntu
environment:
  matrix:
  - RUST_TOOL_CHAIN: stable
  - RUST_TOOL_CHAIN: nightly
before_build:
  - rustc -V
  - cargo -V
  - rustup component add rustfmt-preview
build_script:
  - cargo build --release
test_script:
  - cargo test --release --verbose --features serde
  - cargo doc --no-deps --features serde
  - cargo fmt --all -- --check
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
matrix:
  fast_finish: true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOL_CHAIN}
      - source $HOME/.cargo/env
  -
    matrix:
      only:
        - image: Visual Studio 2017
    install:
      - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      - scoop install rustup
      - refreshenv
      - rustup default %RUST_TOOL_CHAIN%
